//! End-to-end test corpus driven by markdown files.
//!
//! Each test case is one `.md` file under `tests/corpus/<category>/`.
//! A case is a sequence of fenced code blocks; the runner reads them
//! by language and position:
//!
//!   - First ` ```sql` block → schema DDL (optional).
//!   - Last ` ```sql` block  → query to analyze (optional).
//!   - Single ` ```ts` block → full expected codegen output (required;
//!                             the auto-gen banner is stripped before
//!                             comparison).
//!
//! Free-form markdown prose between fences documents the case. The
//! runner treats every other `.md` outside fences as comments.
//!
//! Each category may have a `_setup.sql` file that's applied once at
//! the start (e.g. the migration that creates the shared `users` /
//! `orgs` / `posts` fixture). The runner is order-tolerant — cases
//! that need their own ad-hoc table just include a schema fence; the
//! runner snapshots `pg_class` before/after to clean up exactly the
//! new tables.
//!
//! Requires `DATABASE_URL`.
//!
//! Cram-style promotion: when the actual output diverges from the
//! expected one in the markdown, set `CORPUS_PROMOTE=1` and the runner
//! rewrites the `.md` files in place with the actual TS block. Review
//! the resulting `git diff` to confirm the change is intended.

use similar::{ChangeTag, TextDiff};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use swell_analyzer::{Analyzer, AnalyzerOptions};
use swell_codegen::{render, CodegenOptions};

const HEADER: &str =
    "// Auto-generated by swell. Do not edit.\n// Run `swell gen` or `swell watch` to regenerate.\n\n";

fn promote_enabled() -> bool {
    matches!(
        std::env::var("CORPUS_PROMOTE").as_deref(),
        Ok("1") | Ok("true") | Ok("yes")
    )
}

#[tokio::test(flavor = "current_thread")]
async fn corpus() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus");
    assert!(
        root.is_dir(),
        "corpus dir missing at {}",
        root.display()
    );

    let categories = sorted_subdirs(&root);
    assert!(!categories.is_empty(), "no category subdirs under {}", root.display());

    let url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must point at a dev Postgres");

    let mut failures: Vec<String> = Vec::new();

    for cat_dir in categories {
        let cat_name = cat_dir.file_name().unwrap().to_string_lossy().into_owned();

        // Connect fresh per category — `connect` loads the type
        // catalog at construction time, so applying `_setup.sql` first
        // and then connecting ensures the catalog sees the fixture's
        // enums / domains / composite types.
        let setup_path = cat_dir.join("_setup.sql");
        if setup_path.exists() {
            let setup_sql = std::fs::read_to_string(&setup_path)
                .unwrap_or_else(|e| panic!("read {}: {e}", setup_path.display()));
            apply_setup(&url, &setup_sql).await;
        }

        let schemas = read_schema_list(&cat_dir).unwrap_or_else(|| vec!["public".into()]);
        let an = Analyzer::connect(AnalyzerOptions {
            database_url: url.clone(),
            schemas,
            type_overrides: BTreeMap::new(),
        })
        .await
        .unwrap_or_else(|e| panic!("connect for {cat_name}: {e}"));

        let cases = sorted_files_with_ext(&cat_dir, "md");
        for case_path in cases {
            let case_name = format!(
                "{cat_name}/{}",
                case_path.file_stem().unwrap().to_string_lossy()
            );
            match run_case(&an, &case_path).await {
                Ok(()) => println!("ok      {case_name}"),
                Err(e) => {
                    println!("FAILED  {case_name}");
                    failures.push(format!("{case_name}\n{e}"));
                }
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "\n{} case(s) failed:\n\n{}",
            failures.len(),
            failures.join("\n\n---\n\n"),
        );
    }
}

fn sorted_subdirs(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .map(|e| e.path())
        .collect();
    v.sort();
    v
}

fn sorted_files_with_ext(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some(ext))
        .map(|e| e.path())
        .collect();
    v.sort();
    v
}

/// Read `_schemas.txt` if present — one schema name per line. Defaults
/// to `public`. Used for fixtures that put their objects in a
/// non-default schema (e.g. `billing` for the saas_billing corpus) so
/// the analyzer's catalog picks up their enums / domains / composites.
fn read_schema_list(dir: &Path) -> Option<Vec<String>> {
    let path = dir.join("_schemas.txt");
    let text = std::fs::read_to_string(path).ok()?;
    let names: Vec<String> = text.lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect();
    if names.is_empty() { None } else { Some(names) }
}

async fn apply_setup(url: &str, sql: &str) {
    let (client, conn) = tokio_postgres::connect(url, tokio_postgres::NoTls)
        .await
        .expect("setup connect");
    let h = tokio::spawn(async move {
        let _ = conn.await;
    });
    client.batch_execute(sql).await.expect("apply _setup.sql");
    drop(client);
    let _ = h.await;
}

async fn run_case(an: &Analyzer, path: &Path) -> Result<(), String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("read {}: {e}", path.display()))?;
    let case = parse_case(&text)?;

    // Snapshot tables so we can drop *exactly* what this case creates.
    let before = list_user_tables(an).await?;
    if let Some(schema) = &case.schema {
        an.client
            .batch_execute(schema)
            .await
            .map_err(|e| format!("apply case schema: {e}"))?;
    }
    let after = list_user_tables(an).await?;
    let created: Vec<(String, String)> = after.into_iter()
        .filter(|p| !before.contains(p))
        .collect();

    // Special path: error expectation. Don't continue into codegen if
    // the case is asserting that `analyze` fails.
    if let (Some(sql), Expectation::Err(needle)) = (&case.query, &case.expected) {
        let res = an.analyze(sql).await;
        // Always clean up before returning so a panic later in the
        // pass doesn't leak fixtures from this case.
        if !created.is_empty() {
            drop_tables(an, &created).await?;
        }
        return match res {
            Ok(_) => Err(format!(
                "expected analyze to fail with substring {needle:?}, but it succeeded",
            )),
            Err(e) => {
                let msg = format!("{e:#}");
                if msg.contains(needle) {
                    Ok(())
                } else {
                    Err(format!(
                        "expected error containing {needle:?}, got:\n  {msg}",
                    ))
                }
            }
        };
    }

    let queries = if let Some(sql) = &case.query {
        vec![an.analyze(sql).await.map_err(|e| format!("analyze:\n  {sql}\n  → {e}"))?]
    } else {
        vec![]
    };

    // Tables that need interfaces: every distinct (schema, table) the
    // query's columns or params reference, plus any tables the case's
    // own schema block created (so a schema-only case still has its
    // interface emitted). Sorted for stable output.
    let mut pair_set: std::collections::BTreeSet<(String, String)> = created.iter().cloned().collect();
    for q in &queries {
        for c in &q.columns {
            if let Some(r) = &c.table_ref {
                pair_set.insert((r.schema.clone(), r.table.clone()));
            }
        }
        for p in &q.params {
            if let Some(r) = &p.table_ref {
                pair_set.insert((r.schema.clone(), r.table.clone()));
            }
        }
    }
    let pairs: Vec<(String, String)> = pair_set.into_iter().collect();
    let tables = an.table_schemas(&pairs).await
        .map_err(|e| format!("table_schemas: {e}"))?;

    let actual = render(&queries, CodegenOptions { tables: &tables, ..Default::default() });
    let actual_body = actual.strip_prefix(HEADER).unwrap_or(&actual).to_string();

    if !created.is_empty() {
        drop_tables(an, &created).await?;
    }

    let expected_ts = match &case.expected {
        Expectation::Ts(s) => s,
        // Error cases are handled above; this branch is unreachable.
        Expectation::Err(_) => unreachable!("error cases short-circuit"),
    };
    if actual_body != *expected_ts {
        if promote_enabled() {
            promote(path, &actual_body)?;
            println!("promoted {}", path.display());
            return Ok(());
        }
        return Err(diff(expected_ts, &actual_body));
    }
    Ok(())
}

/// Replace the `ts` fenced block in the case file with the actual
/// output, preserving all surrounding prose and the schema/query
/// blocks. Mirrors `dune promote`.
fn promote(path: &Path, actual: &str) -> Result<(), String> {
    let md = std::fs::read_to_string(path)
        .map_err(|e| format!("read for promote: {e}"))?;
    let mut out = String::with_capacity(md.len() + actual.len());
    let mut lines = md.lines().peekable();
    let mut replaced = false;
    while let Some(line) = lines.next() {
        if !replaced && line.trim_start().starts_with("```")
            && matches!(line.trim_start().strip_prefix("```").map(str::trim), Some("ts") | Some("typescript"))
        {
            out.push_str(line);
            out.push('\n');
            // Skip the original body up to the closing fence.
            for inner in lines.by_ref() {
                if inner.trim_start().starts_with("```") {
                    out.push_str(actual);
                    if !actual.ends_with('\n') { out.push('\n'); }
                    out.push_str(inner);
                    out.push('\n');
                    replaced = true;
                    break;
                }
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    if !replaced {
        return Err("could not find ```ts fence to promote".to_string());
    }
    // Trim any extra trailing newline we may have introduced; markdown
    // files in the repo end with exactly one newline.
    while out.ends_with("\n\n") { out.pop(); }
    std::fs::write(path, out).map_err(|e| format!("write for promote: {e}"))
}

async fn list_user_tables(an: &Analyzer) -> Result<Vec<(String, String)>, String> {
    let rows = an.client
        .query(
            "SELECT n.nspname::text, c.relname::text \
             FROM pg_class c \
             JOIN pg_namespace n ON n.oid = c.relnamespace \
             WHERE c.relkind = 'r' \
               AND n.nspname NOT IN ('pg_catalog', 'information_schema') \
             ORDER BY n.nspname, c.relname",
            &[],
        )
        .await
        .map_err(|e| format!("list_user_tables: {e}"))?;
    Ok(rows.iter().map(|r| (r.get::<_, String>(0), r.get::<_, String>(1))).collect())
}

async fn drop_tables(an: &Analyzer, pairs: &[(String, String)]) -> Result<(), String> {
    if pairs.is_empty() {
        return Ok(());
    }
    let list = pairs.iter()
        .map(|(s, t)| format!("\"{s}\".\"{t}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let stmt = format!("DROP TABLE IF EXISTS {list} CASCADE");
    an.client.batch_execute(&stmt).await
        .map_err(|e| format!("drop_tables: {e}"))
}

enum Expectation {
    /// Compare full generated codegen output (TS).
    Ts(String),
    /// `analyze` must fail; the rendered error must contain this
    /// substring. Use an ```err fence.
    Err(String),
}

struct Case {
    schema: Option<String>,
    query: Option<String>,
    expected: Expectation,
}

/// Walk the markdown, collect fenced code blocks by language.
fn parse_case(md: &str) -> Result<Case, String> {
    let mut sql_blocks: Vec<String> = Vec::new();
    let mut ts_blocks: Vec<String> = Vec::new();
    let mut err_blocks: Vec<String> = Vec::new();
    let mut lines = md.lines();
    while let Some(line) = lines.next() {
        let trimmed = line.trim_start();
        let lang = match trimmed.strip_prefix("```") {
            Some(rest) => rest.trim(),
            None => continue,
        };
        let mut body = String::new();
        for inner in lines.by_ref() {
            if inner.trim_start().starts_with("```") {
                break;
            }
            body.push_str(inner);
            body.push('\n');
        }
        match lang {
            "sql" => sql_blocks.push(body),
            "ts" | "typescript" => ts_blocks.push(body),
            "err" | "error" => err_blocks.push(body),
            _ => {} // ignore other fence languages
        }
    }

    let expected = match (ts_blocks.len(), err_blocks.len()) {
        (1, 0) => Expectation::Ts(ts_blocks.remove(0)),
        (0, 1) => Expectation::Err(err_blocks.remove(0).trim().to_string()),
        (t, e) => return Err(format!(
            "expected exactly one ```ts OR ```err block; found ts={t}, err={e}",
        )),
    };

    let (schema, query) = match sql_blocks.len() {
        0 => (None, None),
        1 => (None, Some(sql_blocks.remove(0).trim().to_string())),
        2 => (Some(sql_blocks.remove(0)), Some(sql_blocks.remove(0).trim().to_string())),
        n => return Err(format!("at most 2 ```sql blocks expected, found {n}")),
    };
    Ok(Case { schema, query, expected })
}

/// Line-by-line diff in unified style. `-` lines were expected,
/// `+` lines are what the runner actually produced. Context is
/// trimmed so the user reads just the relevant region.
fn diff(expected: &str, actual: &str) -> String {
    let mut out = String::new();
    out.push_str("--- expected\n+++ actual\n");
    let diff = TextDiff::from_lines(expected, actual);
    for group in diff.grouped_ops(3) {
        for op in group {
            for change in diff.iter_changes(&op) {
                let sign = match change.tag() {
                    ChangeTag::Delete => '-',
                    ChangeTag::Insert => '+',
                    ChangeTag::Equal  => ' ',
                };
                out.push(sign);
                out.push_str(change.value());
                if !out.ends_with('\n') { out.push('\n'); }
            }
        }
    }
    out.push_str("\nrun with CORPUS_PROMOTE=1 to update the expected block.\n");
    out
}
