//! Codegen: InferredQuery[] → .ts string.
//!
//! Emits a per-package `swell.generated.ts` that augments swell's
//! `Registry` interface via `declare module "swell"`. No runtime code:
//! the file is pure type-level merging. `q` itself comes from
//! `"swell"`; its strict overload reads `keyof Registry`, which the
//! augmentation populates.
//!
//! Usage:
//!
//!   import "./swell.generated";   // loads the augmentation
//!   import { q } from "swell";
//!
//!   const stmt = q("SELECT id, email FROM users WHERE id = $1");
//!   const { rows } = await pool.query(stmt, [userId]);
//!   //      ^? { id: string; email: string }[]

use swell_analyzer::InferredQuery;

const HEADER: &str = "// Auto-generated by swell. Do not edit.\n\
                      // Run `swell gen` or `swell watch` to regenerate.\n\n";

pub struct CodegenOptions<'a> {
    pub runtime_module: &'a str,
    /// Extra `import type { … } from "…"` lines to inject after swell's
    /// own import. Used when per-column overrides reference user types.
    pub extra_imports: &'a [(String, Vec<String>)],
}

impl Default for CodegenOptions<'_> {
    fn default() -> Self {
        Self { runtime_module: "swell", extra_imports: &[] }
    }
}

pub fn render(queries: &[InferredQuery], opts: CodegenOptions<'_>) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    // Side-effect import keeps swell in the import graph so the
    // `declare module` below resolves; the type imports keep `Json` /
    // `SqlText` aliases available to column-override emitters.
    out.push_str(&format!("import {{ type Json, type SqlText }} from \"{}\";\n", opts.runtime_module));
    for (from, names) in opts.extra_imports {
        if names.is_empty() {
            continue;
        }
        let typed: Vec<String> = names.iter().map(|n| format!("type {n}")).collect();
        out.push_str(&format!("import {{ {} }} from \"{}\";\n", typed.join(", "), from));
    }
    out.push('\n');
    // Single-line SQL renders as a bare string-literal property key
    // (`"SELECT 1": { ... }`). Multi-line SQL uses a computed key with
    // a template literal (`[`SELECT...\nFROM...`]: { ... }`) so the SQL
    // keeps its original layout. Bare template literals aren't legal as
    // property keys in any TS parser, but the computed form is.
    out.push_str(&format!("declare module \"{}\" {{\n", opts.runtime_module));
    if queries.is_empty() {
        out.push_str("  interface Registry {}\n");
    } else {
        out.push_str("  interface Registry {\n");
        for q in queries {
            out.push_str(&render_entry(q, "    "));
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n");
    out
}

fn render_entry(q: &InferredQuery, indent: &str) -> String {
    let key = render_key(&q.sql);
    let params = render_params_tuple(q);
    let row = render_row_type(&q.columns);
    format!("{indent}{key}: {{ params: {params}; row: {row} }};\n")
}

/// Render the SQL string as a property key. Single-line SQL becomes a
/// bare string-literal key (`"SELECT 1"`); multi-line SQL becomes a
/// computed key with a template literal (`[\`...\`]`) so the SQL keeps
/// its layout. Both forms produce identical string-literal key types
/// for call-site narrowing.
fn render_key(sql: &str) -> String {
    if sql.contains('\n') {
        format!("[`{}`]", escape_ts_template_literal(sql))
    } else {
        format!("\"{}\"", escape_ts_string(sql))
    }
}

fn render_params_tuple(q: &InferredQuery) -> String {
    if q.params.is_empty() {
        return "[]".to_string();
    }
    // Postgres's PARSE/DESCRIBE doesn't report param nullability — we
    // infer it in `param_nullability.rs` by walking the SQL AST and
    // checking whether `$N` binds directly to a NOT NULL column in
    // INSERT VALUES or UPDATE SET. Anything else stays nullable so
    // callers can pass null where Postgres tolerates it (WHERE,
    // coalesce, etc.). `unknown` is already wide enough to admit null.
    let elems: Vec<String> = q
        .params
        .iter()
        .map(|p| {
            if p.ts_type == "unknown" || !p.nullable {
                p.ts_type.clone()
            } else {
                format!("{} | null", p.ts_type)
            }
        })
        .collect();
    format!("[{}]", elems.join(", "))
}

fn render_row_type(cols: &[swell_analyzer::InferredColumn]) -> String {
    if cols.is_empty() {
        // Write-only statement (no RETURNING / no SELECT) — only `exec` is
        // meaningful. Setting `row: never` causes `one`/`maybe`/`many`/call
        // to type as `never` which makes accidental use visible.
        return "never".to_string();
    }
    let fields: Vec<String> = cols
        .iter()
        .map(|c| {
            let nullable = if c.nullable { " | null" } else { "" };
            format!("{}: {}{}", quote_ident(&c.name), c.ts_type, nullable)
        })
        .collect();
    format!("{{ {} }}", fields.join("; "))
}

fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Escape for a TS template literal (backtick-delimited). Newlines pass
/// through verbatim — that's the whole point. Only backslash, backtick,
/// and the `${` interpolation start need escaping.
fn escape_ts_template_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '`' => out.push_str("\\`"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 && c != '\n' && c != '\t' => {
                out.push_str(&format!("\\u{:04x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out
}

fn quote_ident(name: &str) -> String {
    let is_simple = !name.is_empty()
        && name.chars().next().unwrap().is_ascii_alphabetic()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if is_simple { name.to_string() } else { format!("\"{}\"", escape_ts_string(name)) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use swell_analyzer::{InferredColumn, InferredParam};

    fn q(sql: &str, params: Vec<InferredParam>, columns: Vec<InferredColumn>) -> InferredQuery {
        InferredQuery { sql: sql.into(), params, columns }
    }

    #[test]
    fn extra_imports_render_after_swell_import() {
        let imports = vec![(
            "@/lib/types".to_string(),
            vec!["ImportSchema".to_string(), "JsonSchema".to_string()],
        )];
        let out = render(
            &[],
            CodegenOptions { runtime_module: "swell", extra_imports: &imports },
        );
        assert!(
            out.contains("import { type ImportSchema, type JsonSchema } from \"@/lib/types\";"),
            "expected extra import line, got: {}",
            out
        );
    }

    #[test]
    fn empty_module_emits_empty_registry_augmentation() {
        let out = render(&[], CodegenOptions::default());
        assert!(out.contains("import { type Json, type SqlText } from \"swell\""), "got: {}", out);
        assert!(out.contains("declare module \"swell\" {"), "got: {}", out);
        assert!(out.contains("  interface Registry {}\n"), "got: {}", out);
        assert!(!out.contains("export function q"), "should not emit q; q lives in swell now: {}", out);
    }

    #[test]
    fn entry_no_params() {
        let queries = vec![q(
            "SELECT 1",
            vec![],
            vec![InferredColumn { name: "?column?".into(), oid: 0, nullable: false, ts_type: "number".into() }],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains("    \"SELECT 1\": { params: []; row: { \"?column?\": number } };"),
            "got: {}",
            out
        );
    }

    #[test]
    fn entry_with_params() {
        let queries = vec![q(
            "SELECT id FROM users WHERE id = $1",
            vec![InferredParam { oid: 0, ts_type: "string".into(), nullable: true }],
            vec![InferredColumn { name: "id".into(), oid: 0, nullable: false, ts_type: "string".into() }],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains(
                "    \"SELECT id FROM users WHERE id = $1\": { params: [string | null]; row: { id: string } };"
            ),
            "got: {}",
            out
        );
    }

    #[test]
    fn entry_write_only_query() {
        let queries = vec![q(
            "DELETE FROM users WHERE id = $1",
            vec![InferredParam { oid: 0, ts_type: "string".into(), nullable: true }],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains(
                "    \"DELETE FROM users WHERE id = $1\": { params: [string | null]; row: never };"
            ),
            "got: {}",
            out
        );
    }

    #[test]
    fn multiline_query_renders_as_computed_template_literal_key() {
        // Multi-line SQL uses `[\`...\`]` (a computed key with a template
        // literal) so the SQL keeps its original layout. Bare template
        // literals aren't legal as property keys in any TS parser, but
        // the computed form is.
        let queries = vec![q(
            "SELECT id, email\nFROM users\nWHERE id = $1",
            vec![InferredParam { oid: 0, ts_type: "string".into(), nullable: true }],
            vec![InferredColumn { name: "id".into(), oid: 0, nullable: false, ts_type: "string".into() }],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains("    [`SELECT id, email\nFROM users\nWHERE id = $1`]: { params:"),
            "expected computed template-literal key, got: {}",
            out
        );
    }

    #[test]
    fn template_literal_escapes_backticks_and_interpolation() {
        let queries = vec![q(
            "SELECT '`x`' AS a, '${y}' AS b\nFROM t",
            vec![],
            vec![InferredColumn { name: "a".into(), oid: 0, nullable: false, ts_type: "string".into() }],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("\\`x\\`"), "backtick not escaped: {}", out);
        assert!(out.contains("\\${y}"), "interpolation not escaped: {}", out);
    }

    #[test]
    fn multiple_entries_render_in_one_interface() {
        let queries = vec![
            q("SELECT 1", vec![], vec![InferredColumn { name: "n".into(), oid: 0, nullable: false, ts_type: "number".into() }]),
            q("SELECT 2", vec![], vec![InferredColumn { name: "n".into(), oid: 0, nullable: false, ts_type: "number".into() }]),
        ];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("declare module \"swell\" {\n  interface Registry {\n"), "missing block open: {}", out);
        assert!(out.contains("    \"SELECT 1\": { params: []; row: { n: number } };\n"), "missing entry 1: {}", out);
        assert!(out.contains("    \"SELECT 2\": { params: []; row: { n: number } };\n"), "missing entry 2: {}", out);
        assert!(out.contains("  }\n}\n"), "missing block close: {}", out);
    }

    #[test]
    fn unknown_params_stay_unwidened() {
        // `T | null` widens `unknown` to `unknown` already; don't bother
        // adding the union, it just looks noisy in the generated file.
        let queries = vec![q(
            "SELECT 1 WHERE $1::int = 1",
            vec![InferredParam { oid: 0, ts_type: "unknown".into(), nullable: true }],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("params: [unknown];"), "got: {}", out);
    }

    #[test]
    fn non_null_params_render_without_union() {
        // `nullable: false` means the AST analyzer saw `$N` bind to a
        // NOT NULL column — codegen drops the `| null` widening.
        let queries = vec![q(
            "INSERT INTO t (a) VALUES ($1)",
            vec![InferredParam { oid: 0, ts_type: "string".into(), nullable: false }],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("params: [string];"), "got: {}", out);
    }
}
