//! Codegen: InferredQuery[] → .ts string.
//!
//! Emits a per-package `swell.generated.ts` that:
//!
//!   1. Exports one `interface SchemaTable` per base table referenced
//!      by any registered query (column union across all queries).
//!      Users import these everywhere — `SchedulerCampaigns["id"]`
//!      becomes the single source of truth for an `id` column.
//!   2. Augments swell's `Registry` interface via `declare module
//!      "swell"`. Query entries reference the table types
//!      (`row: { id: SchedulerCampaigns["id"]; … }`) wherever the
//!      column is a direct base-table ref. Computed / cast / aggregate
//!      results inline the raw type — there's no table to point at.
//!
//! No runtime code: the file is pure type-level merging. `q` itself
//! comes from `"swell"`; its strict overload reads `keyof Registry`,
//! which the augmentation populates.
//!
//! Usage:
//!
//!   import "./swell.generated";   // loaded automatically by tsconfig include
//!   import { q } from "swell";
//!
//!   const stmt = q("SELECT id, email FROM users WHERE id = $1");
//!   const { rows } = await pool.query(stmt, [userId]);
//!   //      ^? { id: Users["id"]; email: Users["email"] }[]

use std::collections::BTreeMap;
use swell_analyzer::{InferredColumn, InferredParam, InferredQuery, TableColRef, TableSchema};

const HEADER: &str = "// Auto-generated by swell. Do not edit.\n\
                      // Run `swell gen` or `swell watch` to regenerate.\n\n";

pub struct CodegenOptions<'a> {
    pub runtime_module: &'a str,
    /// Extra `import type { … } from "…"` lines to inject after swell's
    /// own import. Used when per-column overrides reference user types.
    pub extra_imports: &'a [(String, Vec<String>)],
    /// Full schema of every base table referenced by any query.
    /// Codegen emits one `export interface SchemaTable` per entry and
    /// rewrites column references in the registry to `Table["col"]`.
    /// Empty input = inline raw types (legacy behaviour).
    pub tables: &'a [TableSchema],
}

impl Default for CodegenOptions<'_> {
    fn default() -> Self {
        Self { runtime_module: "swell", extra_imports: &[], tables: &[] }
    }
}

pub fn render(queries: &[InferredQuery], opts: CodegenOptions<'_>) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    // Side-effect import keeps swell in the import graph so the
    // `declare module` below resolves; the type imports keep `Json` /
    // `SqlText` aliases available to column-override emitters.
    out.push_str(&format!("import {{ type Json, type SqlText }} from \"{}\";\n", opts.runtime_module));
    for (from, names) in opts.extra_imports {
        if names.is_empty() {
            continue;
        }
        let typed: Vec<String> = names.iter().map(|n| format!("type {n}")).collect();
        out.push_str(&format!("import {{ {} }} from \"{}\";\n", typed.join(", "), from));
    }
    out.push('\n');

    // Sort tables for stable output. Schema-qualified ordering.
    let mut sorted_tables: Vec<&TableSchema> = opts.tables.iter().collect();
    sorted_tables.sort_by(|a, b| (a.schema.as_str(), a.table.as_str())
        .cmp(&(b.schema.as_str(), b.table.as_str())));

    let names = TableNameMap::from(&sorted_tables);

    for t in &sorted_tables {
        out.push_str(&render_table_interface(t, &names));
    }
    if !sorted_tables.is_empty() {
        out.push('\n');
    }

    out.push_str(&format!("declare module \"{}\" {{\n", opts.runtime_module));
    if queries.is_empty() {
        out.push_str("  interface Registry {}\n");
    } else {
        out.push_str("  interface Registry {\n");
        for q in queries {
            out.push_str(&render_entry(q, "    ", &names));
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n");
    out
}

/// Pretty-print a `SchemaTable` name from a `(schema, table)` pair.
/// `scheduler.campaigns` → `SchedulerCampaigns`. `public.users` →
/// `Users` (the default `public` schema is elided for ergonomics).
fn type_name(schema: &str, table: &str) -> String {
    let schema_prefix = if schema == "public" {
        String::new()
    } else {
        pascal_case(schema)
    };
    format!("{}{}", schema_prefix, pascal_case(table))
}

fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Maps (schema, table) → TS identifier, after collision-resolution.
/// Two tables in different schemas sometimes produce the same default
/// PascalCase name (`public.X` + `app.X` both collapse to `X` when we
/// elide `public.`); when that happens, fall back to fully-qualified
/// names for all conflicting entries.
struct TableNameMap {
    by_pair: BTreeMap<(String, String), String>,
}

impl TableNameMap {
    fn from(tables: &[&TableSchema]) -> Self {
        let mut counts: BTreeMap<String, usize> = BTreeMap::new();
        for t in tables {
            *counts.entry(type_name(&t.schema, &t.table)).or_default() += 1;
        }
        let mut by_pair = BTreeMap::new();
        for t in tables {
            let pretty = type_name(&t.schema, &t.table);
            let name = if counts.get(&pretty).copied().unwrap_or(0) > 1 {
                // Disambiguate by including the schema even if it's `public`.
                format!("{}{}", pascal_case(&t.schema), pascal_case(&t.table))
            } else {
                pretty
            };
            by_pair.insert((t.schema.clone(), t.table.clone()), name);
        }
        Self { by_pair }
    }

    fn lookup(&self, schema: &str, table: &str) -> Option<&str> {
        self.by_pair.get(&(schema.to_string(), table.to_string())).map(|s| s.as_str())
    }
}

fn render_table_interface(t: &TableSchema, names: &TableNameMap) -> String {
    // `names` was built from the same `&[TableSchema]` slice — every
    // (schema, table) here MUST be present. Panic rather than emit a
    // nameless `export interface {}` if that invariant ever breaks.
    let name = names.lookup(&t.schema, &t.table)
        .unwrap_or_else(|| panic!("TableNameMap missing entry for {}.{}", t.schema, t.table));
    let mut out = String::new();
    out.push_str(&format!("export interface {name} {{\n"));
    for col in &t.columns {
        let nullable = if col.not_null { "" } else { " | null" };
        out.push_str(&format!(
            "  {}: {}{};\n",
            quote_ident(&col.name),
            col.ts_type,
            nullable,
        ));
    }
    out.push_str("}\n");
    out
}

fn render_entry(q: &InferredQuery, indent: &str, names: &TableNameMap) -> String {
    let key = render_key(&q.sql);
    let params = render_params_tuple(q, names);
    let row = render_row_type(&q.columns, names);
    format!("{indent}{key}: {{ params: {params}; row: {row} }};\n")
}

/// Render the SQL string as a property key. Single-line SQL becomes a
/// bare string-literal key (`"SELECT 1"`); multi-line SQL becomes a
/// computed key with a template literal (`[\`...\`]`) so the SQL keeps
/// its layout. Both forms produce identical string-literal key types
/// for call-site narrowing.
fn render_key(sql: &str) -> String {
    if sql.contains('\n') {
        format!("[`{}`]", escape_ts_template_literal(sql))
    } else {
        format!("\"{}\"", escape_ts_string(sql))
    }
}

fn render_params_tuple(q: &InferredQuery, names: &TableNameMap) -> String {
    if q.params.is_empty() {
        return "[]".to_string();
    }
    // Postgres's PARSE/DESCRIBE doesn't report param nullability — we
    // infer it in `param_nullability.rs` by walking the SQL AST and
    // checking whether `$N` binds directly to a NOT NULL column in
    // INSERT VALUES or UPDATE SET. Anything else stays nullable so
    // callers can pass null where Postgres tolerates it (WHERE,
    // coalesce, etc.). `unknown` is already wide enough to admit null.
    let elems: Vec<String> = q
        .params
        .iter()
        .map(|p| render_param_type(p, names))
        .collect();
    format!("[{}]", elems.join(", "))
}

fn render_param_type(p: &InferredParam, names: &TableNameMap) -> String {
    render_typed(&p.ts_type, p.nullable, p.table_ref.as_ref(), names)
}

fn render_row_type(cols: &[InferredColumn], names: &TableNameMap) -> String {
    if cols.is_empty() {
        // `row: never` makes accidental use of a write-only statement's row
        // shape visible — `one`/`maybe`/`many`/call all type as `never`.
        return "never".to_string();
    }
    let fields: Vec<String> = cols
        .iter()
        .map(|c| format!("{}: {}", quote_ident(&c.name),
            render_typed(&c.ts_type, c.nullable, c.table_ref.as_ref(), names)))
        .collect();
    format!("{{ {} }}", fields.join("; "))
}

/// Shared rendering for query columns and INSERT/UPDATE params: prefer
/// `Table["col"]` whenever a base column is known, fall back to the
/// inferred ts_type otherwise. `unknown` already admits null at the
/// type level so we don't decorate it further.
fn render_typed(
    ts_type: &str, nullable: bool, table_ref: Option<&TableColRef>, names: &TableNameMap,
) -> String {
    let base = table_ref
        .and_then(|r| indexed_table_ref(r, names))
        .unwrap_or_else(|| ts_type.to_string());
    if nullable && base != "unknown" {
        format!("{} | null", base)
    } else {
        base
    }
}

fn indexed_table_ref(r: &TableColRef, names: &TableNameMap) -> Option<String> {
    let name = names.lookup(&r.schema, &r.table)?;
    Some(format!("{}[\"{}\"]", name, escape_ts_string(&r.column)))
}

fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Escape for a TS template literal (backtick-delimited). Newlines pass
/// through verbatim — that's the whole point. Only backslash, backtick,
/// and the `${` interpolation start need escaping.
fn escape_ts_template_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '`' => out.push_str("\\`"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 && c != '\n' && c != '\t' => {
                out.push_str(&format!("\\u{:04x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out
}

fn quote_ident(name: &str) -> String {
    let is_simple = !name.is_empty()
        && name.chars().next().unwrap().is_ascii_alphabetic()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if is_simple { name.to_string() } else { format!("\"{}\"", escape_ts_string(name)) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use swell_analyzer::{InferredColumn, InferredParam, TableSchemaColumn};

    fn q(sql: &str, params: Vec<InferredParam>, columns: Vec<InferredColumn>) -> InferredQuery {
        InferredQuery { sql: sql.into(), params, columns }
    }

    fn col(name: &str, ts: &str, nullable: bool) -> InferredColumn {
        InferredColumn {
            name: name.into(), oid: 0, nullable, ts_type: ts.into(),
            table_ref: None,
        }
    }

    fn col_from(name: &str, ts: &str, nullable: bool, schema: &str, table: &str) -> InferredColumn {
        InferredColumn {
            name: name.into(), oid: 0, nullable, ts_type: ts.into(),
            table_ref: Some(TableColRef {
                schema: schema.into(), table: table.into(), column: name.into(),
            }),
        }
    }

    fn p(ts: &str, nullable: bool) -> InferredParam {
        InferredParam { oid: 0, ts_type: ts.into(), nullable, table_ref: None }
    }

    fn p_from(ts: &str, nullable: bool, schema: &str, table: &str, column: &str) -> InferredParam {
        InferredParam {
            oid: 0, ts_type: ts.into(), nullable,
            table_ref: Some(TableColRef {
                schema: schema.into(), table: table.into(), column: column.into(),
            }),
        }
    }

    fn ts(schema: &str, table: &str, cols: Vec<(&str, &str, bool)>) -> TableSchema {
        TableSchema {
            schema: schema.into(),
            table: table.into(),
            columns: cols.into_iter().map(|(n, t, nn)| TableSchemaColumn {
                name: n.into(), oid: 0, ts_type: t.into(), not_null: nn,
            }).collect(),
        }
    }

    #[test]
    fn extra_imports_render_after_swell_import() {
        let imports = vec![(
            "@/lib/types".to_string(),
            vec!["ImportSchema".to_string(), "JsonSchema".to_string()],
        )];
        let out = render(
            &[],
            CodegenOptions { runtime_module: "swell", extra_imports: &imports, tables: &[] },
        );
        assert!(
            out.contains("import { type ImportSchema, type JsonSchema } from \"@/lib/types\";"),
            "expected extra import line, got: {}",
            out
        );
    }

    #[test]
    fn empty_module_emits_empty_registry_augmentation() {
        let out = render(&[], CodegenOptions::default());
        assert!(out.contains("import { type Json, type SqlText } from \"swell\""), "got: {}", out);
        assert!(out.contains("declare module \"swell\" {"), "got: {}", out);
        assert!(out.contains("  interface Registry {}\n"), "got: {}", out);
        assert!(!out.contains("export function q"), "should not emit q; q lives in swell now: {}", out);
    }

    #[test]
    fn entry_no_params() {
        let queries = vec![q(
            "SELECT 1",
            vec![],
            vec![col("?column?", "number", false)],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains("    \"SELECT 1\": { params: []; row: { \"?column?\": number } };"),
            "got: {}",
            out
        );
    }

    #[test]
    fn entry_with_params() {
        let queries = vec![q(
            "SELECT id FROM users WHERE id = $1",
            vec![p("string", true)],
            vec![col("id", "string", false)],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains(
                "    \"SELECT id FROM users WHERE id = $1\": { params: [string | null]; row: { id: string } };"
            ),
            "got: {}",
            out
        );
    }

    #[test]
    fn entry_write_only_query() {
        let queries = vec![q(
            "DELETE FROM users WHERE id = $1",
            vec![p("string", true)],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains(
                "    \"DELETE FROM users WHERE id = $1\": { params: [string | null]; row: never };"
            ),
            "got: {}",
            out
        );
    }

    #[test]
    fn multiline_query_renders_as_computed_template_literal_key() {
        let queries = vec![q(
            "SELECT id, email\nFROM users\nWHERE id = $1",
            vec![p("string", true)],
            vec![col("id", "string", false)],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(
            out.contains("    [`SELECT id, email\nFROM users\nWHERE id = $1`]: { params:"),
            "expected computed template-literal key, got: {}",
            out
        );
    }

    #[test]
    fn template_literal_escapes_backticks_and_interpolation() {
        let queries = vec![q(
            "SELECT '`x`' AS a, '${y}' AS b\nFROM t",
            vec![],
            vec![col("a", "string", false)],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("\\`x\\`"), "backtick not escaped: {}", out);
        assert!(out.contains("\\${y}"), "interpolation not escaped: {}", out);
    }

    #[test]
    fn multiple_entries_render_in_one_interface() {
        let queries = vec![
            q("SELECT 1", vec![], vec![col("n", "number", false)]),
            q("SELECT 2", vec![], vec![col("n", "number", false)]),
        ];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("declare module \"swell\" {\n  interface Registry {\n"), "missing block open: {}", out);
        assert!(out.contains("    \"SELECT 1\": { params: []; row: { n: number } };\n"), "missing entry 1: {}", out);
        assert!(out.contains("    \"SELECT 2\": { params: []; row: { n: number } };\n"), "missing entry 2: {}", out);
        assert!(out.contains("  }\n}\n"), "missing block close: {}", out);
    }

    #[test]
    fn unknown_params_stay_unwidened() {
        let queries = vec![q(
            "SELECT 1 WHERE $1::int = 1",
            vec![p("unknown", true)],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("params: [unknown];"), "got: {}", out);
    }

    #[test]
    fn non_null_params_render_without_union() {
        let queries = vec![q(
            "INSERT INTO t (a) VALUES ($1)",
            vec![p("string", false)],
            vec![],
        )];
        let out = render(&queries, CodegenOptions::default());
        assert!(out.contains("params: [string];"), "got: {}", out);
    }

    #[test]
    fn tables_render_as_exported_interfaces() {
        let tables = vec![
            ts("scheduler", "campaigns", vec![
                ("id", "number", true),
                ("name", "string", true),
                ("owner_id", "string", false),  // nullable
            ]),
        ];
        let out = render(&[], CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("export interface SchedulerCampaigns {\n"), "got: {}", out);
        assert!(out.contains("  id: number;\n"), "got: {}", out);
        assert!(out.contains("  name: string;\n"), "got: {}", out);
        assert!(out.contains("  owner_id: string | null;\n"), "got: {}", out);
    }

    #[test]
    fn public_schema_is_elided_from_type_name() {
        let tables = vec![ts("public", "users", vec![("id", "string", true)])];
        let out = render(&[], CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("export interface Users {"), "got: {}", out);
        assert!(!out.contains("PublicUsers"), "should elide public schema, got: {}", out);
    }

    #[test]
    fn column_ref_in_query_uses_indexed_access() {
        let tables = vec![ts("scheduler", "campaigns", vec![
            ("id", "number", true),
            ("name", "string", true),
        ])];
        let queries = vec![q(
            "SELECT id, name FROM scheduler.campaigns WHERE id = $1",
            vec![p("number", true)],
            vec![
                col_from("id", "number", false, "scheduler", "campaigns"),
                col_from("name", "string", false, "scheduler", "campaigns"),
            ],
        )];
        let out = render(&queries, CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("row: { id: SchedulerCampaigns[\"id\"]; name: SchedulerCampaigns[\"name\"] }"),
            "got: {}", out);
    }

    #[test]
    fn param_ref_uses_indexed_access() {
        let tables = vec![ts("public", "orgs", vec![
            ("id", "string", true),
            ("name", "string", true),
        ])];
        let queries = vec![q(
            "INSERT INTO orgs (id, name) VALUES ($1, $2)",
            vec![
                p_from("string", false, "public", "orgs", "id"),
                p_from("string", false, "public", "orgs", "name"),
            ],
            vec![],
        )];
        let out = render(&queries, CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("params: [Orgs[\"id\"], Orgs[\"name\"]]"),
            "got: {}", out);
    }

    #[test]
    fn nullable_join_widens_table_ref() {
        // LEFT JOIN makes a NOT NULL base column nullable in the result.
        // Codegen keeps the table ref but unions with null.
        let tables = vec![ts("public", "posts", vec![("body", "string", true)])];
        let queries = vec![q(
            "SELECT p.body FROM users u LEFT JOIN posts p ON p.author_id = u.id",
            vec![],
            vec![col_from("body", "string", true, "public", "posts")],
        )];
        let out = render(&queries, CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("row: { body: Posts[\"body\"] | null }"), "got: {}", out);
    }

    #[test]
    fn cross_schema_disambiguation_no_collision() {
        // public.campaigns elides to "Campaigns"; scheduler.campaigns
        // becomes "SchedulerCampaigns". These don't actually collide,
        // so codegen keeps the public-elided name.
        let tables = vec![
            ts("public", "campaigns", vec![("id", "string", true)]),
            ts("scheduler", "campaigns", vec![("id", "number", true)]),
        ];
        let out = render(&[], CodegenOptions {
            tables: &tables, ..Default::default()
        });
        assert!(out.contains("export interface Campaigns "), "got: {}", out);
        assert!(out.contains("export interface SchedulerCampaigns "), "got: {}", out);
    }

    #[test]
    fn same_pretty_name_in_different_schemas_disambiguates() {
        // Same default-stripped pretty name in two non-public schemas →
        // include the schema prefix on both to disambiguate.
        let tables = vec![
            ts("scheduler", "campaigns", vec![("id", "number", true)]),
            // Synthetic collision: a fake schema whose name maps to
            // the same PascalCase as `scheduler` after stripping
            // doesn't exist in practice — instead, simulate a direct
            // tie by injecting two non-public schemas with identical
            // table names but distinct schema names.
            ts("scheduler_beta", "campaigns", vec![("id", "number", true)]),
        ];
        let out = render(&[], CodegenOptions {
            tables: &tables, ..Default::default()
        });
        // Both already get unique names without further work
        // (SchedulerCampaigns vs SchedulerBetaCampaigns).
        assert!(out.contains("export interface SchedulerCampaigns "), "got: {}", out);
        assert!(out.contains("export interface SchedulerBetaCampaigns "), "got: {}", out);
    }
}
