//! Codegen: `InferredQuery[]` → `.ts` string.
//!
//! Emits a `swell.generated.ts` that
//!   1. exports one `interface SchemaTable` per referenced base table, and
//!   2. augments `Registry` via `declare module "@dialo/swell"`.
//!
//! Pure type-level merging — no runtime code. `q` lives in
//! `@dialo/swell`; its strict overload reads `keyof Registry`.

use std::collections::BTreeMap;
use swell_analyzer::{
    InferredColumn, InferredParam, InferredQuery, RowVariant, TableColRef, TableSchema,
};

const HEADER: &str = "// Auto-generated by swell. Do not edit.\n\
                      // Run `swell gen` or `swell watch` to regenerate.\n\n";

const RUNTIME_MODULE: &str = "@dialo/swell";

#[derive(Default)]
pub struct CodegenOptions<'a> {
    /// Extra `import type { … } from "…"` lines (for per-column user
    /// type overrides).
    pub extra_imports: &'a [(String, Vec<String>)],
    /// Schema of every referenced base table. Empty = inline raw
    /// types instead of `Table["col"]` rewriting.
    pub tables: &'a [TableSchema],
}

/// Sort tables by (schema, table) and build the collision-resolved name map.
fn sorted_with_names(tables: &[TableSchema]) -> (Vec<&TableSchema>, TableNameMap) {
    let mut sorted: Vec<&TableSchema> = tables.iter().collect();
    sorted.sort_by(|a, b| {
        (a.schema.as_str(), a.table.as_str()).cmp(&(b.schema.as_str(), b.table.as_str()))
    });
    let names = build_name_map(&sorted);
    (sorted, names)
}

fn render_row(q: &InferredQuery, names: &TableNameMap, tables: &[TableSchema]) -> String {
    if q.row_variants.is_empty() {
        render_row_type(&q.columns, names, tables)
    } else {
        render_row_with_variants(&q.columns, &q.row_variants, names, tables)
    }
}

/// Just the table interfaces — no banner / imports / Registry. Used
/// by the markdown-corpus runner's `# Common types` block.
pub fn render_table_interfaces(tables: &[TableSchema]) -> String {
    let (sorted, names) = sorted_with_names(tables);
    sorted
        .iter()
        .map(|t| render_table_interface(t, &names))
        .collect()
}

/// One `$N: type` line per param plus a `result: …` line, for the
/// markdown corpus runner's per-test expected blocks.
pub fn render_query_compact(q: &InferredQuery, tables: &[TableSchema]) -> String {
    let (_, names) = sorted_with_names(tables);
    let mut out = String::new();
    for (i, p) in q.params.iter().enumerate() {
        out += &format!("${}: {}\n", i + 1, render_param_type(p));
    }
    out += &format!("result: {}\n", render_row(q, &names, tables));
    out
}

pub fn render(queries: &[InferredQuery], opts: CodegenOptions<'_>) -> String {
    let mut out = String::from(HEADER);
    // Side-effect import keeps swell in the graph so `declare module`
    // resolves; the type aliases stay available for override emitters.
    out += &format!("import {{ type Json, type SqlText }} from \"{RUNTIME_MODULE}\";\n");
    for (from, names) in opts.extra_imports {
        if names.is_empty() {
            continue;
        }
        let typed = names
            .iter()
            .map(|n| format!("type {n}"))
            .collect::<Vec<_>>()
            .join(", ");
        out += &format!("import {{ {typed} }} from \"{from}\";\n");
    }
    out.push('\n');

    let (sorted_tables, names) = sorted_with_names(opts.tables);
    for t in &sorted_tables {
        out += &render_table_interface(t, &names);
    }
    if !sorted_tables.is_empty() {
        out.push('\n');
    }

    out += &format!("declare module \"{RUNTIME_MODULE}\" {{\n");
    if queries.is_empty() {
        out += "  interface Registry {}\n";
    } else {
        out += "  interface Registry {\n";
        for q in queries {
            out += &render_entry(q, "    ", &names, opts.tables);
        }
        out += "  }\n";
    }
    out += "}\n";
    out
}

/// `scheduler.campaigns` → `SchedulerCampaigns`; `public.users` →
/// `Users` (public is elided).
fn type_name(schema: &str, table: &str) -> String {
    let prefix = if schema == "public" {
        String::new()
    } else {
        pascal_case(schema)
    };
    format!("{prefix}{}", pascal_case(table))
}

fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// `(schema, table)` → TS identifier with collisions resolved by
/// reinstating the schema prefix on conflicting entries.
type TableNameMap = BTreeMap<(String, String), String>;

fn build_name_map(tables: &[&TableSchema]) -> TableNameMap {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for t in tables {
        *counts.entry(type_name(&t.schema, &t.table)).or_default() += 1;
    }
    let mut out = BTreeMap::new();
    for t in tables {
        let pretty = type_name(&t.schema, &t.table);
        let name = if counts.get(&pretty).copied().unwrap_or(0) > 1 {
            format!("{}{}", pascal_case(&t.schema), pascal_case(&t.table))
        } else {
            pretty
        };
        out.insert((t.schema.clone(), t.table.clone()), name);
    }
    out
}

fn name_lookup<'a>(names: &'a TableNameMap, schema: &str, table: &str) -> Option<&'a str> {
    names
        .get(&(schema.to_string(), table.to_string()))
        .map(|s| s.as_str())
}

fn render_table_interface(t: &TableSchema, names: &TableNameMap) -> String {
    // names is built from the same slice; every (schema, table) must
    // be present.
    let name = name_lookup(names, &t.schema, &t.table)
        .unwrap_or_else(|| panic!("TableNameMap missing entry for {}.{}", t.schema, t.table));
    let mut out = format!("export interface {name} {{\n");
    for col in &t.columns {
        let nn = if col.not_null { "" } else { " | null" };
        out += &format!("  {}: {}{nn};\n", quote_ident(&col.name), col.ts_type);
    }
    out += "}\n";
    out
}

fn render_entry(
    q: &InferredQuery,
    indent: &str,
    names: &TableNameMap,
    tables: &[TableSchema],
) -> String {
    let key = render_key(&q.sql);
    let params = render_params_tuple(q);
    let row = render_row(q, names, tables);
    format!("{indent}{key}: {{ params: {params}; row: {row} }};\n")
}

/// Discriminated row union for FULL OUTER JOIN and GROUPING SETS.
/// Non-overridden columns within a variant render as non-null —
/// they're known present in that specific arm.
fn render_row_with_variants(
    cols: &[InferredColumn],
    variants: &[RowVariant],
    names: &TableNameMap,
    tables: &[TableSchema],
) -> String {
    let alts: Vec<String> = variants
        .iter()
        .map(|v| {
            let fields: Vec<String> = cols
                .iter()
                .map(|c| {
                    let ts = v.overrides.get(&c.name).cloned().unwrap_or_else(|| {
                        render_typed(&c.ts_type, false, c.table_ref.as_ref(), names, tables)
                    });
                    format!("{}: {}", quote_ident(&c.name), ts)
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        })
        .collect();
    alts.join(" | ")
}

/// Single-line SQL → `"…"` key; multi-line → `[\`…\`]` computed key
/// so the SQL keeps its layout. Both forms narrow identically.
fn render_key(sql: &str) -> String {
    if sql.contains('\n') {
        format!("[`{}`]", escape_ts_template_literal(sql))
    } else {
        format!("\"{}\"", escape_ts_string(sql))
    }
}

fn render_params_tuple(q: &InferredQuery) -> String {
    let elems: Vec<String> = q.params.iter().map(render_param_type).collect();
    format!("[{}]", elems.join(", "))
}

/// Params skip the `Table["col"]` substitution columns get — the
/// table interfaces are rendered for the read direction, but params
/// take the write (serialize) shape carried by `p.ts_type`.
fn render_param_type(p: &InferredParam) -> String {
    if p.nullable && p.ts_type != "unknown" {
        format!("{} | null", p.ts_type)
    } else {
        p.ts_type.clone()
    }
}

fn render_row_type(
    cols: &[InferredColumn],
    names: &TableNameMap,
    tables: &[TableSchema],
) -> String {
    // `row: never` surfaces accidental use of write-only statements.
    if cols.is_empty() {
        return "never".to_string();
    }
    let fields_of = |slice: &[InferredColumn]| -> String {
        slice
            .iter()
            .map(|c| {
                format!(
                    "{}: {}",
                    quote_ident(&c.name),
                    render_typed(&c.ts_type, c.nullable, c.table_ref.as_ref(), names, tables)
                )
            })
            .collect::<Vec<_>>()
            .join("; ")
    };
    // SELECT *-style: contiguous prefix matches a table's full column
    // list → emit `Table` (intersected with `{ rest }` for trailing
    // extras).
    if let Some((table_name, used)) = detect_star_prefix(cols, tables, names) {
        let rest = &cols[used..];
        return if rest.is_empty() {
            table_name
        } else {
            format!("{} & {{ {} }}", table_name, fields_of(rest))
        };
    }
    format!("{{ {} }}", fields_of(cols))
}

/// Returns `(table_name, consumed)` when a contiguous prefix of `cols`
/// matches a table's full column list (names, order, nullability all
/// agree).
fn detect_star_prefix(
    cols: &[InferredColumn],
    tables: &[TableSchema],
    names: &TableNameMap,
) -> Option<(String, usize)> {
    let r = cols.first()?.table_ref.as_ref()?;
    let table = tables
        .iter()
        .find(|t| t.schema == r.schema && t.table == r.table)?;
    let n = table.columns.len();
    if cols.len() < n {
        return None;
    }
    // Nullability must agree with the interface; an override would
    // be lost by switching to the interface form.
    let matches = cols[..n].iter().zip(&table.columns).all(|(c, tc)| {
        c.name == tc.name
            && c.nullable == !tc.not_null
            && c.table_ref.as_ref().is_some_and(|t| {
                t.schema == table.schema && t.table == table.table && t.column == tc.name
            })
    });
    if !matches {
        return None;
    }
    Some((
        name_lookup(names, &table.schema, &table.table)?.to_string(),
        n,
    ))
}

/// Prefer `Table["col"]` for known base columns, falling back to the
/// inferred ts_type. Appends `| null` only when our verdict is wider
/// than what the interface already encodes (outer-join / override
/// widening) — avoids `T | null | null` noise.
fn render_typed(
    ts_type: &str,
    nullable: bool,
    table_ref: Option<&TableColRef>,
    names: &TableNameMap,
    tables: &[TableSchema],
) -> String {
    let base = table_ref
        .and_then(|r| indexed_table_ref(r, names))
        .unwrap_or_else(|| ts_type.to_string());
    if !nullable || base == "unknown" {
        return base;
    }
    let interface_already_nullable = table_ref.is_some_and(|r| {
        tables
            .iter()
            .find(|t| t.schema == r.schema && t.table == r.table)
            .and_then(|t| t.columns.iter().find(|c| c.name == r.column))
            .is_some_and(|c| !c.not_null)
    });
    if interface_already_nullable {
        base
    } else {
        format!("{base} | null")
    }
}

fn indexed_table_ref(r: &TableColRef, names: &TableNameMap) -> Option<String> {
    let name = name_lookup(names, &r.schema, &r.table)?;
    Some(format!("{}[\"{}\"]", name, escape_ts_string(&r.column)))
}

fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// TS template literal escape — newlines pass through (that's the
/// point); only `\\`, `` ` ``, and `${` need handling.
fn escape_ts_template_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '`' => out.push_str("\\`"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 && c != '\n' && c != '\t' => {
                out.push_str(&format!("\\u{:04x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out
}

fn quote_ident(name: &str) -> String {
    let is_simple = !name.is_empty()
        && name.chars().next().unwrap().is_ascii_alphabetic()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if is_simple {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts_string(name))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use swell_analyzer::{InferredColumn, InferredParam, TableSchemaColumn};

    fn q(sql: &str, params: Vec<InferredParam>, columns: Vec<InferredColumn>) -> InferredQuery {
        InferredQuery {
            sql: sql.into(),
            params,
            columns,
            row_variants: Vec::new(),
        }
    }

    fn col(name: &str, ts: &str, nullable: bool) -> InferredColumn {
        InferredColumn {
            name: name.into(),
            nullable,
            ts_type: ts.into(),
            table_ref: None,
        }
    }

    fn tref(schema: &str, table: &str, column: &str) -> TableColRef {
        TableColRef {
            schema: schema.into(),
            table: table.into(),
            column: column.into(),
        }
    }

    fn col_from(name: &str, ts: &str, nullable: bool, schema: &str, table: &str) -> InferredColumn {
        InferredColumn {
            table_ref: Some(tref(schema, table, name)),
            ..col(name, ts, nullable)
        }
    }

    fn p(ts: &str, nullable: bool) -> InferredParam {
        InferredParam {
            ts_type: ts.into(),
            nullable,
            table_ref: None,
        }
    }

    fn p_from(ts: &str, nullable: bool, schema: &str, table: &str, column: &str) -> InferredParam {
        InferredParam {
            table_ref: Some(tref(schema, table, column)),
            ..p(ts, nullable)
        }
    }

    fn ts(schema: &str, table: &str, cols: Vec<(&str, &str, bool)>) -> TableSchema {
        TableSchema {
            schema: schema.into(),
            table: table.into(),
            columns: cols
                .into_iter()
                .map(|(n, t, nn)| TableSchemaColumn {
                    name: n.into(),
                    ts_type: t.into(),
                    not_null: nn,
                })
                .collect(),
        }
    }

    fn with_tables(tables: &[TableSchema]) -> CodegenOptions<'_> {
        CodegenOptions {
            tables,
            ..Default::default()
        }
    }

    fn render_one(sql: &str, params: Vec<InferredParam>, cols: Vec<InferredColumn>) -> String {
        render(&[q(sql, params, cols)], CodegenOptions::default())
    }

    fn render_one_with(
        sql: &str,
        params: Vec<InferredParam>,
        cols: Vec<InferredColumn>,
        tables: &[TableSchema],
    ) -> String {
        render(&[q(sql, params, cols)], with_tables(tables))
    }

    #[track_caller]
    fn assert_has(out: &str, needle: &str) {
        assert!(out.contains(needle), "expected `{needle}` in:\n{out}");
    }

    #[track_caller]
    fn assert_lacks(out: &str, needle: &str) {
        assert!(
            !out.contains(needle),
            "did not expect `{needle}` in:\n{out}"
        );
    }

    #[test]
    fn extra_imports_render_after_swell_import() {
        let imports = [(
            "@/lib/types".into(),
            vec!["ImportSchema".into(), "JsonSchema".into()],
        )];
        let opts = CodegenOptions {
            extra_imports: &imports,
            tables: &[],
        };
        let out = render(&[], opts);
        assert_has(
            &out,
            "import { type ImportSchema, type JsonSchema } from \"@/lib/types\";",
        );
    }

    #[test]
    fn empty_module_emits_empty_registry_augmentation() {
        let out = render(&[], CodegenOptions::default());
        assert_has(
            &out,
            "import { type Json, type SqlText } from \"@dialo/swell\"",
        );
        assert_has(&out, "declare module \"@dialo/swell\" {");
        assert_has(&out, "  interface Registry {}\n");
        // q lives in swell now; codegen should never emit it.
        assert_lacks(&out, "export function q");
    }

    #[test]
    fn entry_no_params() {
        let out = render_one("SELECT 1", vec![], vec![col("?column?", "number", false)]);
        assert_has(
            &out,
            "    \"SELECT 1\": { params: []; row: { \"?column?\": number } };",
        );
    }

    #[test]
    fn entry_with_params() {
        let out = render_one(
            "SELECT id FROM users WHERE id = $1",
            vec![p("string", true)],
            vec![col("id", "string", false)],
        );
        assert_has(&out, "    \"SELECT id FROM users WHERE id = $1\": { params: [string | null]; row: { id: string } };");
    }

    #[test]
    fn entry_write_only_query() {
        let out = render_one(
            "DELETE FROM users WHERE id = $1",
            vec![p("string", true)],
            vec![],
        );
        assert_has(
            &out,
            "    \"DELETE FROM users WHERE id = $1\": { params: [string | null]; row: never };",
        );
    }

    #[test]
    fn multiline_query_renders_as_computed_template_literal_key() {
        let out = render_one(
            "SELECT id, email\nFROM users\nWHERE id = $1",
            vec![p("string", true)],
            vec![col("id", "string", false)],
        );
        assert_has(
            &out,
            "    [`SELECT id, email\nFROM users\nWHERE id = $1`]: { params:",
        );
    }

    #[test]
    fn template_literal_escapes_backticks_and_interpolation() {
        let out = render_one(
            "SELECT '`x`' AS a, '${y}' AS b\nFROM t",
            vec![],
            vec![col("a", "string", false)],
        );
        assert_has(&out, "\\`x\\`");
        assert_has(&out, "\\${y}");
    }

    #[test]
    fn multiple_entries_render_in_one_interface() {
        let mk = |sql| q(sql, vec![], vec![col("n", "number", false)]);
        let out = render(&[mk("SELECT 1"), mk("SELECT 2")], CodegenOptions::default());
        assert_has(
            &out,
            "declare module \"@dialo/swell\" {\n  interface Registry {\n",
        );
        assert_has(
            &out,
            "    \"SELECT 1\": { params: []; row: { n: number } };\n",
        );
        assert_has(
            &out,
            "    \"SELECT 2\": { params: []; row: { n: number } };\n",
        );
        assert_has(&out, "  }\n}\n");
    }

    #[test]
    fn unknown_params_stay_unwidened() {
        let out = render_one(
            "SELECT 1 WHERE $1::int = 1",
            vec![p("unknown", true)],
            vec![],
        );
        assert_has(&out, "params: [unknown];");
    }

    #[test]
    fn non_null_params_render_without_union() {
        let out = render_one(
            "INSERT INTO t (a) VALUES ($1)",
            vec![p("string", false)],
            vec![],
        );
        assert_has(&out, "params: [string];");
    }

    #[test]
    fn tables_render_as_exported_interfaces() {
        let cols = vec![
            ("id", "number", true),
            ("name", "string", true),
            ("owner_id", "string", false),
        ];
        let tables = vec![ts("scheduler", "campaigns", cols)];
        let out = render(&[], with_tables(&tables));
        assert_has(&out, "export interface SchedulerCampaigns {\n");
        assert_has(&out, "  id: number;\n");
        assert_has(&out, "  name: string;\n");
        assert_has(&out, "  owner_id: string | null;\n");
    }

    #[test]
    fn public_schema_is_elided_from_type_name() {
        let tables = vec![ts("public", "users", vec![("id", "string", true)])];
        let out = render(&[], with_tables(&tables));
        assert_has(&out, "export interface Users {");
        assert_lacks(&out, "PublicUsers");
    }

    #[test]
    fn column_ref_in_query_uses_indexed_access() {
        // Partial selection (table has 3 cols, query picks 2) so the
        // SELECT-* short-circuit doesn't fire and we exercise the
        // indexed-access path.
        let cols = vec![
            ("id", "number", true),
            ("name", "string", true),
            ("owner_id", "string", false),
        ];
        let tables = vec![ts("scheduler", "campaigns", cols)];
        let cf = |n, ts| col_from(n, ts, false, "scheduler", "campaigns");
        let out = render_one_with(
            "SELECT id, name FROM scheduler.campaigns WHERE id = $1",
            vec![p("number", true)],
            vec![cf("id", "number"), cf("name", "string")],
            &tables,
        );
        assert_has(
            &out,
            "row: { id: SchedulerCampaigns[\"id\"]; name: SchedulerCampaigns[\"name\"] }",
        );
    }

    #[test]
    fn param_ref_keeps_inferred_write_direction_ts_type() {
        // The Table interface is rendered with read-direction (parse)
        // types; a `types.by_name` split (e.g. timestamp parses to
        // Spacetime, serializes from Date) would otherwise leak the
        // read shape into INSERT/UPDATE positions. Params keep the
        // analyzer's write-direction `ts_type` verbatim.
        let tables = vec![ts("public", "events", vec![("at", "Spacetime", true)])];
        let out = render_one_with(
            "INSERT INTO events (at) VALUES ($1)",
            vec![p_from("Date", false, "public", "events", "at")],
            vec![],
            &tables,
        );
        assert_has(&out, "params: [Date]");
        assert_lacks(&out, "params: [Events[");
    }

    #[test]
    fn column_ref_still_uses_indexed_access_after_param_fix() {
        // Sanity: param rendering changes must not regress column
        // rendering. The extra column keeps the SELECT-* short-circuit
        // from firing.
        let tables = vec![ts(
            "public",
            "events",
            vec![("at", "Spacetime", true), ("kind", "string", true)],
        )];
        let out = render_one_with(
            "SELECT at FROM events",
            vec![],
            vec![col_from("at", "Spacetime", false, "public", "events")],
            &tables,
        );
        assert_has(&out, "row: { at: Events[\"at\"] }");
    }

    #[test]
    fn nullable_join_widens_table_ref() {
        // LEFT JOIN widens a NOT NULL base column to nullable; codegen
        // keeps the table ref but unions with null.
        let tables = vec![ts("public", "posts", vec![("body", "string", true)])];
        let out = render_one_with(
            "SELECT p.body FROM users u LEFT JOIN posts p ON p.author_id = u.id",
            vec![],
            vec![col_from("body", "string", true, "public", "posts")],
            &tables,
        );
        assert_has(&out, "row: { body: Posts[\"body\"] | null }");
    }

    #[test]
    fn cross_schema_disambiguation_no_collision() {
        // public.campaigns elides to "Campaigns"; scheduler.campaigns
        // becomes "SchedulerCampaigns" — no collision, keep both.
        let tables = vec![
            ts("public", "campaigns", vec![("id", "string", true)]),
            ts("scheduler", "campaigns", vec![("id", "number", true)]),
        ];
        let out = render(&[], with_tables(&tables));
        assert_has(&out, "export interface Campaigns ");
        assert_has(&out, "export interface SchedulerCampaigns ");
    }

    #[test]
    fn same_pretty_name_in_different_schemas_disambiguates() {
        // Two non-public schemas with the same table name disambiguate
        // by including the schema prefix on both.
        let tables = vec![
            ts("scheduler", "campaigns", vec![("id", "number", true)]),
            ts("scheduler_beta", "campaigns", vec![("id", "number", true)]),
        ];
        let out = render(&[], with_tables(&tables));
        assert_has(&out, "export interface SchedulerCampaigns ");
        assert_has(&out, "export interface SchedulerBetaCampaigns ");
    }
}
