// Auto-generated by swell. Do not edit.
// Run `swell gen` or `swell watch` to regenerate.

import { createTypedSql, type AnyDriver, type Json, type TypedSql } from "swell";

// Per-package query registry — one entry per analysed `sql.<method>` call site.
export type QueryRegistry = {
};

export type Sql = TypedSql<QueryRegistry>;

/** Bind the registry to a driver. Accepts a postgres.js `Sql`
*  or a node-pg `Pool`/`Client`/`PoolClient`. */
export function createSql(driver: AnyDriver): Sql {
  return createTypedSql<QueryRegistry>(driver);
}
